; Auto-generated. Do not edit!


(cl:in-package hrwros_msgs-msg)


;//! \htmlinclude CounterWithDelayResult.msg.html

(cl:defclass <CounterWithDelayResult> (roslisp-msg-protocol:ros-message)
  ((result_message
    :reader result_message
    :initarg :result_message
    :type cl:string
    :initform ""))
)

(cl:defclass CounterWithDelayResult (<CounterWithDelayResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CounterWithDelayResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CounterWithDelayResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hrwros_msgs-msg:<CounterWithDelayResult> is deprecated: use hrwros_msgs-msg:CounterWithDelayResult instead.")))

(cl:ensure-generic-function 'result_message-val :lambda-list '(m))
(cl:defmethod result_message-val ((m <CounterWithDelayResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hrwros_msgs-msg:result_message-val is deprecated.  Use hrwros_msgs-msg:result_message instead.")
  (result_message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CounterWithDelayResult>) ostream)
  "Serializes a message object of type '<CounterWithDelayResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'result_message))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'result_message))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CounterWithDelayResult>) istream)
  "Deserializes a message object of type '<CounterWithDelayResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result_message) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'result_message) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CounterWithDelayResult>)))
  "Returns string type for a message object of type '<CounterWithDelayResult>"
  "hrwros_msgs/CounterWithDelayResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CounterWithDelayResult)))
  "Returns string type for a message object of type 'CounterWithDelayResult"
  "hrwros_msgs/CounterWithDelayResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CounterWithDelayResult>)))
  "Returns md5sum for a message object of type '<CounterWithDelayResult>"
  "be8a5eb8699d93f379b287dcfc6e376c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CounterWithDelayResult)))
  "Returns md5sum for a message object of type 'CounterWithDelayResult"
  "be8a5eb8699d93f379b287dcfc6e376c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CounterWithDelayResult>)))
  "Returns full string definition for message of type '<CounterWithDelayResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string result_message		# Result message: simple string message for the result.~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CounterWithDelayResult)))
  "Returns full string definition for message of type 'CounterWithDelayResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string result_message		# Result message: simple string message for the result.~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CounterWithDelayResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'result_message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CounterWithDelayResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CounterWithDelayResult
    (cl:cons ':result_message (result_message msg))
))
