; Auto-generated. Do not edit!


(cl:in-package hrwros_msgs-msg)


;//! \htmlinclude CounterWithDelayGoal.msg.html

(cl:defclass <CounterWithDelayGoal> (roslisp-msg-protocol:ros-message)
  ((num_counts
    :reader num_counts
    :initarg :num_counts
    :type cl:integer
    :initform 0))
)

(cl:defclass CounterWithDelayGoal (<CounterWithDelayGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CounterWithDelayGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CounterWithDelayGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hrwros_msgs-msg:<CounterWithDelayGoal> is deprecated: use hrwros_msgs-msg:CounterWithDelayGoal instead.")))

(cl:ensure-generic-function 'num_counts-val :lambda-list '(m))
(cl:defmethod num_counts-val ((m <CounterWithDelayGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hrwros_msgs-msg:num_counts-val is deprecated.  Use hrwros_msgs-msg:num_counts instead.")
  (num_counts m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CounterWithDelayGoal>) ostream)
  "Serializes a message object of type '<CounterWithDelayGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'num_counts)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'num_counts)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'num_counts)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'num_counts)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CounterWithDelayGoal>) istream)
  "Deserializes a message object of type '<CounterWithDelayGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'num_counts)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'num_counts)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'num_counts)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'num_counts)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CounterWithDelayGoal>)))
  "Returns string type for a message object of type '<CounterWithDelayGoal>"
  "hrwros_msgs/CounterWithDelayGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CounterWithDelayGoal)))
  "Returns string type for a message object of type 'CounterWithDelayGoal"
  "hrwros_msgs/CounterWithDelayGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CounterWithDelayGoal>)))
  "Returns md5sum for a message object of type '<CounterWithDelayGoal>"
  "42f5ddfe2ee41298918bff5bf724cca8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CounterWithDelayGoal)))
  "Returns md5sum for a message object of type 'CounterWithDelayGoal"
  "42f5ddfe2ee41298918bff5bf724cca8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CounterWithDelayGoal>)))
  "Returns full string definition for message of type '<CounterWithDelayGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 num_counts		# Goal message: number of counts to count up to.~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CounterWithDelayGoal)))
  "Returns full string definition for message of type 'CounterWithDelayGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 num_counts		# Goal message: number of counts to count up to.~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CounterWithDelayGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CounterWithDelayGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CounterWithDelayGoal
    (cl:cons ':num_counts (num_counts msg))
))
