// Auto-generated. Do not edit!

// (in-package hrwros_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CounterWithDelayGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.num_counts = null;
    }
    else {
      if (initObj.hasOwnProperty('num_counts')) {
        this.num_counts = initObj.num_counts
      }
      else {
        this.num_counts = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CounterWithDelayGoal
    // Serialize message field [num_counts]
    bufferOffset = _serializer.uint32(obj.num_counts, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CounterWithDelayGoal
    let len;
    let data = new CounterWithDelayGoal(null);
    // Deserialize message field [num_counts]
    data.num_counts = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'hrwros_msgs/CounterWithDelayGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '42f5ddfe2ee41298918bff5bf724cca8';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint32 num_counts		# Goal message: number of counts to count up to.
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CounterWithDelayGoal(null);
    if (msg.num_counts !== undefined) {
      resolved.num_counts = msg.num_counts;
    }
    else {
      resolved.num_counts = 0
    }

    return resolved;
    }
};

module.exports = CounterWithDelayGoal;
