// Generated by gencpp from file hrwros_msgs/ConvertMetresToFeet.msg
// DO NOT EDIT!


#ifndef HRWROS_MSGS_MESSAGE_CONVERTMETRESTOFEET_H
#define HRWROS_MSGS_MESSAGE_CONVERTMETRESTOFEET_H

#include <ros/service_traits.h>


#include <hrwros_msgs/ConvertMetresToFeetRequest.h>
#include <hrwros_msgs/ConvertMetresToFeetResponse.h>


namespace hrwros_msgs
{

struct ConvertMetresToFeet
{

typedef ConvertMetresToFeetRequest Request;
typedef ConvertMetresToFeetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConvertMetresToFeet
} // namespace hrwros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hrwros_msgs::ConvertMetresToFeet > {
  static const char* value()
  {
    return "8ee6357200ff4b8dfb11e637c7e317c0";
  }

  static const char* value(const ::hrwros_msgs::ConvertMetresToFeet&) { return value(); }
};

template<>
struct DataType< ::hrwros_msgs::ConvertMetresToFeet > {
  static const char* value()
  {
    return "hrwros_msgs/ConvertMetresToFeet";
  }

  static const char* value(const ::hrwros_msgs::ConvertMetresToFeet&) { return value(); }
};


// service_traits::MD5Sum< ::hrwros_msgs::ConvertMetresToFeetRequest> should match
// service_traits::MD5Sum< ::hrwros_msgs::ConvertMetresToFeet >
template<>
struct MD5Sum< ::hrwros_msgs::ConvertMetresToFeetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hrwros_msgs::ConvertMetresToFeet >::value();
  }
  static const char* value(const ::hrwros_msgs::ConvertMetresToFeetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrwros_msgs::ConvertMetresToFeetRequest> should match
// service_traits::DataType< ::hrwros_msgs::ConvertMetresToFeet >
template<>
struct DataType< ::hrwros_msgs::ConvertMetresToFeetRequest>
{
  static const char* value()
  {
    return DataType< ::hrwros_msgs::ConvertMetresToFeet >::value();
  }
  static const char* value(const ::hrwros_msgs::ConvertMetresToFeetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hrwros_msgs::ConvertMetresToFeetResponse> should match
// service_traits::MD5Sum< ::hrwros_msgs::ConvertMetresToFeet >
template<>
struct MD5Sum< ::hrwros_msgs::ConvertMetresToFeetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hrwros_msgs::ConvertMetresToFeet >::value();
  }
  static const char* value(const ::hrwros_msgs::ConvertMetresToFeetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrwros_msgs::ConvertMetresToFeetResponse> should match
// service_traits::DataType< ::hrwros_msgs::ConvertMetresToFeet >
template<>
struct DataType< ::hrwros_msgs::ConvertMetresToFeetResponse>
{
  static const char* value()
  {
    return DataType< ::hrwros_msgs::ConvertMetresToFeet >::value();
  }
  static const char* value(const ::hrwros_msgs::ConvertMetresToFeetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HRWROS_MSGS_MESSAGE_CONVERTMETRESTOFEET_H
