// Generated by gencpp from file hrwros_msgs/CounterWithDelayResult.msg
// DO NOT EDIT!


#ifndef HRWROS_MSGS_MESSAGE_COUNTERWITHDELAYRESULT_H
#define HRWROS_MSGS_MESSAGE_COUNTERWITHDELAYRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrwros_msgs
{
template <class ContainerAllocator>
struct CounterWithDelayResult_
{
  typedef CounterWithDelayResult_<ContainerAllocator> Type;

  CounterWithDelayResult_()
    : result_message()  {
    }
  CounterWithDelayResult_(const ContainerAllocator& _alloc)
    : result_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_message_type;
  _result_message_type result_message;





  typedef boost::shared_ptr< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> const> ConstPtr;

}; // struct CounterWithDelayResult_

typedef ::hrwros_msgs::CounterWithDelayResult_<std::allocator<void> > CounterWithDelayResult;

typedef boost::shared_ptr< ::hrwros_msgs::CounterWithDelayResult > CounterWithDelayResultPtr;
typedef boost::shared_ptr< ::hrwros_msgs::CounterWithDelayResult const> CounterWithDelayResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator1> & lhs, const ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator2> & rhs)
{
  return lhs.result_message == rhs.result_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator1> & lhs, const ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hrwros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be8a5eb8699d93f379b287dcfc6e376c";
  }

  static const char* value(const ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe8a5eb8699d93f3ULL;
  static const uint64_t static_value2 = 0x79b287dcfc6e376cULL;
};

template<class ContainerAllocator>
struct DataType< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrwros_msgs/CounterWithDelayResult";
  }

  static const char* value(const ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string result_message		# Result message: simple string message for the result.\n"
;
  }

  static const char* value(const ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CounterWithDelayResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrwros_msgs::CounterWithDelayResult_<ContainerAllocator>& v)
  {
    s << indent << "result_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRWROS_MSGS_MESSAGE_COUNTERWITHDELAYRESULT_H
