(cl:defpackage hrwros_msgs-srv
  (:use )
  (:export
   "CONVERTMETRESTOFEET"
   "<CONVERTMETRESTOFEET-REQUEST>"
   "CONVERTMETRESTOFEET-REQUEST"
   "<CONVERTMETRESTOFEET-RESPONSE>"
   "CONVERTMETRESTOFEET-RESPONSE"
  ))

